// Hospital data
export const allHospitalsData = [
    // Hospitals - Cardiology
    {
        id: 'hosp1',
        name: 'Heart Care Center',
        category: 'Hospital',
        type: 'Cardiology Hospital',
        specialty: 'Cardiology',
        distance: 2.1,
        time: 15,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 289,
        imageUrl: 'https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 3500,
        experience: '20 years',
        contact: '+91 9939069288',
        workingHours: '24/7 Emergency Services',
        about: 'Heart Care Center is a specialized cardiology hospital providing advanced cardiac care with state-of-the-art equipment and experienced cardiologists.',
        distanceText: '2.1 km away',
        doctors: ['doc1', 'doc2', 'doc3'] // Cardiology doctors
    },
    {
        id: 'hosp2',
        name: 'Cardiac Care Institute',
        category: 'Clinic',
        type: 'Cardiology Clinic',
        specialty: 'Cardiology',
        distance: 3.4,
        time: 25,
        location: 'Guntur',
        rating: 4.8,
        reviews: 234,
        imageUrl: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 2800,
        experience: '18 years',
        contact: '+91 9876543211',
        workingHours: 'Monday-Saturday, 8.00 AM-8.00 PM',
        about: 'Cardiac Care Institute offers comprehensive cardiac services including diagnostic procedures, interventional cardiology, and cardiac rehabilitation.',
        distanceText: '3.4 km away',
        doctors: ['doc2', 'doc3'] // Cardiology doctors
    },
    // Dental Clinics
    {
        id: 'hosp3',
        name: 'Bright Smile Dental',
        category: 'Dental',
        type: 'Dental Clinic',
        specialty: 'Dentistry',
        distance: 1.8,
        time: 12,
        location: 'Vijayawada',
        rating: 4.7,
        reviews: 156,
        imageUrl: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 1200,
        experience: '15 years',
        contact: '+91 9876543212',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Bright Smile Dental provides comprehensive dental care with modern technology and experienced professionals. We offer cosmetic dentistry and orthodontic treatments.',
        distanceText: '1.8 km away',
        doctors: ['doc4', 'doc5'] // Dental doctors
    },
    {
        id: 'hosp4',
        name: 'Perfect Smile Dental',
        category: 'Dental',
        type: 'Dental Hospital',
        specialty: 'Dentistry',
        distance: 2.7,
        time: 20,
        location: 'Tenali',
        rating: 4.8,
        reviews: 134,
        imageUrl: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 950,
        experience: '12 years',
        contact: '+91 9876543213',
        workingHours: 'Monday-Saturday, 9.00 AM-6.00 PM',
        about: 'Perfect Smile Dental is a modern dental hospital offering advanced treatments including dental implants, root canals, and cosmetic procedures.',
        distanceText: '2.7 km away',
        doctors: ['doc5', 'doc6'] // Dental doctors
    },
    // Hospitals - Pulmonary
    {
        id: 'hosp5',
        name: 'Lung Care Center',
        category: 'Hospital',
        type: 'Pulmonary Hospital',
        specialty: 'Pulmonary',
        distance: 2.9,
        time: 22,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 178,
        imageUrl: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 2200,
        experience: '16 years',
        contact: '+91 9876543214',
        workingHours: 'Monday-Friday, 8.00 AM-6.00 PM',
        about: 'Lung Care Center specializes in respiratory disorders and pulmonary medicine. We provide comprehensive care for asthma, COPD, and other lung conditions.',
        distanceText: '2.9 km away',
        doctors: ['doc7', 'doc8'] // Pulmonary doctors
    },
    {
        id: 'hosp6',
        name: 'Respiratory Health Institute',
        category: 'Clinic',
        type: 'Pulmonary Clinic',
        specialty: 'Pulmonary',
        distance: 3.6,
        time: 28,
        location: 'Guntur',
        rating: 4.7,
        reviews: 145,
        imageUrl: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 1800,
        experience: '14 years',
        contact: '+91 9876543215',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Respiratory Health Institute offers advanced pulmonary care with specialized equipment for respiratory function testing and treatment.',
        distanceText: '3.6 km away',
        doctors: ['doc8'] // Pulmonary doctors
    },
    // Hospitals - General
    {
        id: 'hosp7',
        name: 'Sunrise Health Hospital',
        category: 'Hospital',
        type: 'General Hospital',
        specialty: 'General Medicine',
        distance: 1.5,
        time: 10,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 345,
        imageUrl: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 4500,
        experience: '25 years',
        contact: '+91 9876543216',
        workingHours: '24/7 Emergency Services',
        about: 'Sunrise Health Hospital is a state-of-the-art medical facility providing comprehensive healthcare services. We are committed to excellence in patient care.',
        distanceText: '1.5 km away',
        doctors: ['doc9', 'doc10'] // General medicine doctors
    },
    {
        id: 'hosp8',
        name: 'City General Hospital',
        category: 'Hospital',
        type: 'General Hospital',
        specialty: 'General Medicine',
        distance: 2.3,
        time: 18,
        location: 'Tenali',
        rating: 4.8,
        reviews: 298,
        imageUrl: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        isFavorite: false,
        patients: 3800,
        experience: '22 years',
        contact: '+91 9876543217',
        workingHours: '24/7 Emergency Services',
        about: 'City General Hospital provides comprehensive medical care with a focus on community health. We offer emergency services and specialized treatments.',
        distanceText: '2.3 km away',
        doctors: ['doc10'] // General medicine doctors
    },
    // Hospitals - Neurology
    {
        id: 'hosp9',
        name: 'Brain & Spine Center',
        category: 'Hospital',
        type: 'Neurology Hospital',
        specialty: 'Neurology',
        distance: 2.8,
        time: 22,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 189,
        imageUrl: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 2800,
        experience: '18 years',
        contact: '+91 9876543218',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM',
        about: 'Brain & Spine Center is a specialized neurology hospital offering advanced treatment for neurological disorders, stroke care, and neurosurgical procedures.',
        distanceText: '2.8 km away',
        doctors: ['doc11', 'doc12'] // Neurology doctors
    },
    {
        id: 'hosp10',
        name: 'Neurological Institute',
        category: 'Clinic',
        type: 'Neurology Clinic',
        specialty: 'Neurology',
        distance: 3.2,
        time: 25,
        location: 'Guntur',
        rating: 4.8,
        reviews: 167,
        imageUrl: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 2200,
        experience: '16 years',
        contact: '+91 9876543219',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Neurological Institute provides comprehensive neurological care including epilepsy treatment, movement disorders, and neuro-rehabilitation services.',
        distanceText: '3.2 km away',
        doctors: ['doc12'] // Neurology doctors
    },
    // Hospitals - Gastroenterology
    {
        id: 'hosp11',
        name: 'Digestive Health Center',
        category: 'Hospital',
        type: 'Gastroenterology Hospital',
        specialty: 'Gastroenterology',
        distance: 2.1,
        time: 16,
        location: 'Vijayawada',
        rating: 4.7,
        reviews: 145,
        imageUrl: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        isFavorite: false,
        patients: 1900,
        experience: '14 years',
        contact: '+91 9876543220',
        workingHours: 'Monday-Friday, 8.00 AM-6.00 PM',
        about: 'Digestive Health Center specializes in gastrointestinal disorders and endoscopy procedures. We provide advanced treatment for digestive system conditions.',
        distanceText: '2.1 km away',
        doctors: ['doc13', 'doc14'] // Gastroenterology doctors
    },
    {
        id: 'hosp12',
        name: 'Gastro Care Institute',
        category: 'Clinic',
        type: 'Gastroenterology Clinic',
        specialty: 'Gastroenterology',
        distance: 2.9,
        time: 22,
        location: 'Tenali',
        rating: 4.8,
        reviews: 134,
        imageUrl: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 1600,
        experience: '12 years',
        contact: '+91 9876543221',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Gastro Care Institute offers comprehensive gastrointestinal care including colonoscopy, liver disease treatment, and inflammatory bowel disease management.',
        distanceText: '2.9 km away',
        doctors: ['doc14'] // Gastroenterology doctors
    },
    // Laboratories
    {
        id: 'hosp13',
        name: 'Advanced Diagnostics Lab',
        category: 'Laboratory',
        type: 'Diagnostic Laboratory',
        specialty: 'Pathology',
        distance: 1.9,
        time: 14,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 189,
        imageUrl: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 2500,
        experience: '18 years',
        contact: '+91 9876543222',
        workingHours: 'Monday-Saturday, 7.00 AM-8.00 PM',
        about: 'Advanced Diagnostics Lab provides comprehensive laboratory testing services with state-of-the-art equipment and accurate results for all types of medical tests.',
        distanceText: '1.9 km away',
        doctors: ['doc15', 'doc16'] // Pathology doctors
    },
    {
        id: 'hosp14',
        name: 'Precision Pathology Lab',
        category: 'Laboratory',
        type: 'Pathology Laboratory',
        specialty: 'Pathology',
        distance: 2.8,
        time: 21,
        location: 'Guntur',
        rating: 4.7,
        reviews: 167,
        imageUrl: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        isFavorite: false,
        patients: 2100,
        experience: '15 years',
        contact: '+91 9876543223',
        workingHours: 'Monday-Friday, 8.00 AM-6.00 PM',
        about: 'Precision Pathology Lab specializes in pathological testing and diagnostic services. We provide accurate and timely results for better patient care.',
        distanceText: '2.8 km away',
        doctors: ['doc16'] // Pathology doctors
    },
    // Vaccination Centers
    {
        id: 'hosp15',
        name: 'Immunization Center',
        category: 'Vaccination',
        type: 'Vaccination Center',
        specialty: 'Immunization',
        distance: 2.2,
        time: 16,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 234,
        imageUrl: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 3200,
        experience: '20 years',
        contact: '+91 9876543224',
        workingHours: 'Monday-Saturday, 8.00 AM-6.00 PM',
        about: 'Immunization Center provides comprehensive vaccination services for all age groups. We offer routine immunizations and travel vaccines with expert care.',
        distanceText: '2.2 km away',
        doctors: ['doc17', 'doc18'] // Immunization specialists
    },
    {
        id: 'hosp16',
        name: 'Vaccine Care Clinic',
        category: 'Vaccination',
        type: 'Vaccination Clinic',
        specialty: 'Immunization',
        distance: 3.1,
        time: 23,
        location: 'Tenali',
        rating: 4.8,
        reviews: 198,
        imageUrl: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 2800,
        experience: '17 years',
        contact: '+91 9876543225',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Vaccine Care Clinic specializes in child and adult immunization programs. We ensure safe and effective vaccination with proper follow-up care.',
        distanceText: '3.1 km away',
        doctors: ['doc18'] // Immunization specialists
    },
    // Ayurvedic Centers
    {
        id: 'hosp17',
        name: 'Green Leaf Ayurvedic Center',
        category: 'Ayurvedic',
        type: 'Ayurvedic Clinic',
        specialty: 'Traditional Medicine',
        distance: 3.5,
        time: 28,
        location: 'Vijayawada',
        rating: 4.6,
        reviews: 156,
        imageUrl: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        isFavorite: false,
        patients: 1800,
        experience: '15 years',
        contact: '+91 9876543226',
        workingHours: 'Monday-Saturday, 8.00 AM-6.00 PM',
        about: 'Green Leaf Ayurvedic Center offers traditional Ayurvedic treatments and therapies. We provide holistic healing through ancient Indian medicine practices.',
        distanceText: '3.5 km away',
        doctors: [] // No specific doctors for Ayurvedic centers
    },
    {
        id: 'hosp18',
        name: 'Patanjali Ayurvedic Center',
        category: 'Ayurvedic',
        type: 'Ayurvedic Hospital',
        specialty: 'Traditional Medicine',
        distance: 4.2,
        time: 32,
        location: 'Guntur',
        rating: 4.7,
        reviews: 189,
        imageUrl: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 2200,
        experience: '18 years',
        contact: '+91 9876543227',
        workingHours: 'Monday-Saturday, 7.00 AM-7.00 PM',
        about: 'Patanjali Ayurvedic Center provides comprehensive Ayurvedic treatments including Panchakarma, herbal medicines, and lifestyle counseling.',
        distanceText: '4.2 km away',
        doctors: [] // No specific doctors for Ayurvedic centers
    },
    // Pharmacies
    {
        id: 'hosp19',
        name: 'City Central Pharmacy',
        category: 'Pharmacy',
        type: 'Medical Pharmacy',
        specialty: 'Pharmaceuticals',
        distance: 0.8,
        time: 5,
        location: 'Vijayawada',
        rating: 4.5,
        reviews: 120,
        imageUrl: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 3000,
        experience: '5 years',
        contact: '+91 9876543228',
        workingHours: 'Open 24/7',
        about: 'City Central Pharmacy provides prescription medications, over-the-counter drugs, and health care products. We offer home delivery services.',
        distanceText: '0.8 km away',
        doctors: [] // No doctors for pharmacies
    },
    {
        id: 'hosp20',
        name: 'Apollo Pharmacy',
        category: 'Pharmacy',
        type: 'Chain Pharmacy',
        specialty: 'Pharmaceuticals',
        distance: 1.5,
        time: 12,
        location: 'Guntur',
        rating: 4.6,
        reviews: 180,
        imageUrl: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        isFavorite: false,
        patients: 4000,
        experience: '10 years',
        contact: '+91 9876543229',
        workingHours: 'Open 24/7',
        about: 'Apollo Pharmacy is a trusted chain pharmacy offering quality medications, health supplements, and professional pharmaceutical consultation.',
        distanceText: '1.5 km away',
        doctors: [] // No doctors for pharmacies
    }
]; 