// Doctor data
export const allDoctorsData = [
    // Cardiology Doctors
    {
        id: 'doc1',
        name: 'Dr. Sarah Khan',
        type: 'Cardiologist',
        specialty: 'Cardiologist',
        distance: 2.5,
        time: 15,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 89,
        imageUrl: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1200,
        experience: '15 years',
        contact: '+91 9876543001',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM',
        about: 'Dr. Sarah Khan is a board-certified cardiologist with over 15 years of experience in treating cardiovascular diseases. She specializes in interventional cardiology and has performed over 500 successful procedures.',
        distanceText: '2.5 km away'
    },
    {
        id: 'doc2',
        name: 'Dr. Rajesh Kumar',
        type: 'Cardiologist',
        specialty: 'Cardiologist',
        distance: 3.2,
        time: 20,
        location: 'Guntur',
        rating: 4.9,
        reviews: 156,
        imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1500,
        experience: '18 years',
        contact: '+91 9876543002',
        workingHours: 'Monday-Saturday, 10.00 AM-7.00 PM',
        about: 'Dr. Rajesh Kumar is a senior cardiologist specializing in preventive cardiology and heart disease management. He emphasizes lifestyle modifications alongside medical treatment.',
        distanceText: '3.2 km away'
    },
    {
        id: 'doc3',
        name: 'Dr. Priya Sharma',
        type: 'Cardiologist',
        specialty: 'Cardiologist',
        distance: 4.1,
        time: 25,
        location: 'Tenali',
        rating: 4.7,
        reviews: 78,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 900,
        experience: '12 years',
        contact: '+91 9876543003',
        workingHours: 'Monday-Friday, 8.00 AM-5.00 PM',
        about: 'Dr. Priya Sharma is a cardiologist with expertise in pediatric cardiology and congenital heart defects. She provides compassionate care to patients of all ages.',
        distanceText: '4.1 km away'
    },
    // Dentistry Doctors
    {
        id: 'doc4',
        name: 'Dr. Amit Patel',
        type: 'Dentist',
        specialty: 'Dentist',
        distance: 1.8,
        time: 12,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 134,
        imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1100,
        experience: '14 years',
        contact: '+91 9876543004',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Dr. Amit Patel is a cosmetic dentist specializing in smile makeovers and dental implants. He uses advanced technology to provide pain-free dental care.',
        distanceText: '1.8 km away'
    },
    {
        id: 'doc5',
        name: 'Dr. Sneha Reddy',
        type: 'Dentist',
        specialty: 'Dentist',
        distance: 2.3,
        time: 18,
        location: 'Guntur',
        rating: 4.8,
        reviews: 98,
        imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 950,
        experience: '11 years',
        contact: '+91 9876543005',
        workingHours: 'Monday-Saturday, 10.00 AM-7.00 PM',
        about: 'Dr. Sneha Reddy is a pediatric dentist who creates a comfortable environment for children. She specializes in preventive dental care and cavity treatment.',
        distanceText: '2.3 km away'
    },
    {
        id: 'doc6',
        name: 'Dr. Ramesh Kumar',
        type: 'Dentist',
        specialty: 'Dentist',
        distance: 3.5,
        time: 25,
        location: 'Tenali',
        rating: 4.7,
        reviews: 87,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 800,
        experience: '16 years',
        contact: '+91 9876543006',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM',
        about: 'Dr. Ramesh Kumar is an orthodontist specializing in braces and Invisalign treatment. He helps patients achieve perfectly aligned smiles.',
        distanceText: '3.5 km away'
    },
    // Pulmonary Doctors
    {
        id: 'doc7',
        name: 'Dr. Arjun Singh',
        type: 'Pulmonologist',
        specialty: 'Pulmonologist',
        distance: 2.1,
        time: 16,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 145,
        imageUrl: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1200,
        experience: '16 years',
        contact: '+91 9876543007',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM',
        about: 'Dr. Arjun Singh is a pulmonologist specializing in respiratory disorders and sleep medicine. He provides comprehensive care for asthma, COPD, and other lung conditions.',
        distanceText: '2.1 km away'
    },
    {
        id: 'doc8',
        name: 'Dr. Kavita Verma',
        type: 'Pulmonologist',
        specialty: 'Pulmonologist',
        distance: 3.8,
        time: 28,
        location: 'Guntur',
        rating: 4.9,
        reviews: 167,
        imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1300,
        experience: '19 years',
        contact: '+91 9876543008',
        workingHours: 'Monday-Friday, 9.00 AM-5.00 PM',
        about: 'Dr. Kavita Verma is a senior pulmonologist with expertise in critical care medicine. She has extensive experience in treating complex respiratory conditions.',
        distanceText: '3.8 km away'
    },
    // General Medicine Doctors
    {
        id: 'doc9',
        name: 'Dr. Suresh Rao',
        type: 'General Physician',
        specialty: 'General Physician',
        distance: 1.5,
        time: 10,
        location: 'Vijayawada',
        rating: 4.7,
        reviews: 234,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 2000,
        experience: '22 years',
        contact: '+91 9876543009',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Dr. Suresh Rao is a family medicine specialist providing comprehensive primary care for patients of all ages. He focuses on preventive medicine and chronic disease management.',
        distanceText: '1.5 km away'
    },
    {
        id: 'doc10',
        name: 'Dr. Meera Iyer',
        type: 'General Physician',
        specialty: 'General Physician',
        distance: 2.7,
        time: 20,
        location: 'Tenali',
        rating: 4.8,
        reviews: 198,
        imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1800,
        experience: '18 years',
        contact: '+91 9876543010',
        workingHours: 'Monday-Friday, 8.00 AM-5.00 PM',
        about: 'Dr. Meera Iyer is a general physician known for her patient-centered approach. She provides holistic care and emphasizes the importance of lifestyle modifications.',
        distanceText: '2.7 km away'
    },
    // Neurology Doctors
    {
        id: 'doc11',
        name: 'Dr. Vikram Malhotra',
        type: 'Neurologist',
        specialty: 'Neurologist',
        distance: 2.8,
        time: 22,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 156,
        imageUrl: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1100,
        experience: '20 years',
        contact: '+91 9876543011',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM',
        about: 'Dr. Vikram Malhotra is a leading neurologist specializing in stroke treatment and neurological disorders. His research has contributed to several breakthrough treatments.',
        distanceText: '2.8 km away'
    },
    {
        id: 'doc12',
        name: 'Dr. Anjali Desai',
        type: 'Neurologist',
        specialty: 'Neurologist',
        distance: 3.4,
        time: 26,
        location: 'Guntur',
        rating: 4.8,
        reviews: 134,
        imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 950,
        experience: '17 years',
        contact: '+91 9876543012',
        workingHours: 'Monday-Friday, 10.00 AM-6.00 PM',
        about: 'Dr. Anjali Desai is a neurologist specializing in epilepsy and movement disorders. She provides comprehensive care for patients with complex neurological conditions.',
        distanceText: '3.4 km away'
    },
    // Gastroenterology Doctors
    {
        id: 'doc13',
        name: 'Dr. Harish Gupta',
        type: 'Gastroenterologist',
        specialty: 'Gastroenterologist',
        distance: 1.9,
        time: 14,
        location: 'Vijayawada',
        rating: 4.7,
        reviews: 178,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1300,
        experience: '19 years',
        contact: '+91 9876543013',
        workingHours: 'Monday-Saturday, 9.00 AM-6.00 PM',
        about: 'Dr. Harish Gupta is a gastroenterologist specializing in digestive disorders and endoscopy procedures. He provides advanced treatment for gastrointestinal conditions.',
        distanceText: '1.9 km away'
    },
    {
        id: 'doc14',
        name: 'Dr. Sunita Kapoor',
        type: 'Gastroenterologist',
        specialty: 'Gastroenterologist',
        distance: 2.6,
        time: 19,
        location: 'Tenali',
        rating: 4.8,
        reviews: 145,
        imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1000,
        experience: '15 years',
        contact: '+91 9876543014',
        workingHours: 'Monday-Friday, 8.00 AM-5.00 PM',
        about: 'Dr. Sunita Kapoor is a gastroenterologist with expertise in liver diseases and inflammatory bowel conditions. She provides personalized treatment plans.',
        distanceText: '2.6 km away'
    },
    // Laboratory Doctors
    {
        id: 'doc15',
        name: 'Dr. Deepak Sharma',
        type: 'Pathologist',
        specialty: 'Pathologist',
        distance: 2.3,
        time: 17,
        location: 'Vijayawada',
        rating: 4.8,
        reviews: 112,
        imageUrl: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 800,
        experience: '16 years',
        contact: '+91 9876543015',
        workingHours: 'Monday-Friday, 9.00 AM-6.00 PM',
        about: 'Dr. Deepak Sharma is a pathologist specializing in clinical pathology and laboratory medicine. He ensures accurate diagnosis through advanced laboratory testing.',
        distanceText: '2.3 km away'
    },
    {
        id: 'doc16',
        name: 'Dr. Rekha Menon',
        type: 'Pathologist',
        specialty: 'Pathologist',
        distance: 3.1,
        time: 23,
        location: 'Guntur',
        rating: 4.7,
        reviews: 98,
        imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 700,
        experience: '14 years',
        contact: '+91 9876543016',
        workingHours: 'Monday-Friday, 10.00 AM-6.00 PM',
        about: 'Dr. Rekha Menon is a pathologist with expertise in cytopathology and molecular diagnostics. She provides precise diagnostic services.',
        distanceText: '3.1 km away'
    },
    // Vaccination Specialists
    {
        id: 'doc17',
        name: 'Dr. Manoj Kumar',
        type: 'Immunologist',
        specialty: 'Immunologist',
        distance: 1.7,
        time: 11,
        location: 'Vijayawada',
        rating: 4.9,
        reviews: 189,
        imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1500,
        experience: '18 years',
        contact: '+91 9876543017',
        workingHours: 'Monday-Saturday, 9.00 AM-7.00 PM',
        about: 'Dr. Manoj Kumar is an immunologist specializing in vaccination and immunization programs. He provides comprehensive immunization services for all age groups.',
        distanceText: '1.7 km away'
    },
    {
        id: 'doc18',
        name: 'Dr. Lakshmi Devi',
        type: 'Pediatrician',
        specialty: 'Pediatrician',
        distance: 2.4,
        time: 18,
        location: 'Tenali',
        rating: 4.8,
        reviews: 156,
        imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        isFavorite: false,
        patients: 1200,
        experience: '15 years',
        contact: '+91 9876543018',
        workingHours: 'Monday-Friday, 8.00 AM-5.00 PM',
        about: 'Dr. Lakshmi Devi is a pediatrician specializing in child immunization and vaccination schedules. She ensures children receive proper vaccination protection.',
        distanceText: '2.4 km away'
    }
]; 