// Sample Data
export const doctorsData = [
    // Cardiology Doctors
    {
        id: 'doc1',
        name: 'Dr. Sarah Khan',
        specialty: 'Cardiologist',
        location: 'Vijayawada',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1200,
        experience: '15 years',
        reviews: 89,
        contact: '+91 9876543001',
        about: 'Dr. Sarah Khan is a board-certified cardiologist with over 15 years of experience in treating cardiovascular diseases. She specializes in interventional cardiology and has performed over 500 successful procedures.',
        distance: '2.5 km away'
    },
    {
        id: 'doc2',
        name: 'Dr. Rajesh Kumar',
        specialty: 'Cardiologist',
        location: 'Guntur',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        patients: 1500,
        experience: '18 years',
        reviews: 156,
        contact: '+91 9876543002',
        about: 'Dr. Rajesh Kumar is a senior cardiologist specializing in preventive cardiology and heart disease management. He emphasizes lifestyle modifications alongside medical treatment.',
        distance: '3.2 km away'
    },
    {
        id: 'doc3',
        name: 'Dr. Priya Sharma',
        specialty: 'Cardiologist',
        location: 'Tenali',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        patients: 900,
        experience: '12 years',
        reviews: 78,
        contact: '+91 9876543003',
        about: 'Dr. Priya Sharma is a cardiologist with expertise in pediatric cardiology and congenital heart defects. She provides compassionate care to patients of all ages.',
        distance: '4.1 km away'
    },
    // Dentistry Doctors
    {
        id: 'doc4',
        name: 'Dr. Amit Patel',
        specialty: 'Dentist',
        location: 'Vijayawada',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        patients: 1100,
        experience: '14 years',
        reviews: 134,
        contact: '+91 9876543004',
        about: 'Dr. Amit Patel is a cosmetic dentist specializing in smile makeovers and dental implants. He uses advanced technology to provide pain-free dental care.',
        distance: '1.8 km away'
    },
    {
        id: 'doc5',
        name: 'Dr. Sneha Reddy',
        specialty: 'Dentist',
        location: 'Guntur',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        patients: 950,
        experience: '11 years',
        reviews: 98,
        contact: '+91 9876543005',
        about: 'Dr. Sneha Reddy is a pediatric dentist who creates a comfortable environment for children. She specializes in preventive dental care and cavity treatment.',
        distance: '2.3 km away'
    },
    {
        id: 'doc6',
        name: 'Dr. Ramesh Kumar',
        specialty: 'Dentist',
        location: 'Tenali',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        patients: 800,
        experience: '16 years',
        reviews: 87,
        contact: '+91 9876543006',
        about: 'Dr. Ramesh Kumar is an orthodontist specializing in braces and Invisalign treatment. He helps patients achieve perfectly aligned smiles.',
        distance: '3.5 km away'
    },
    // Pulmonary Doctors
    {
        id: 'doc7',
        name: 'Dr. Arjun Singh',
        specialty: 'Pulmonologist',
        location: 'Vijayawada',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1200,
        experience: '16 years',
        reviews: 145,
        contact: '+91 9876543007',
        about: 'Dr. Arjun Singh is a pulmonologist specializing in respiratory disorders and sleep medicine. He provides comprehensive care for asthma, COPD, and other lung conditions.',
        distance: '2.1 km away'
    },
    {
        id: 'doc8',
        name: 'Dr. Kavita Verma',
        specialty: 'Pulmonologist',
        location: 'Guntur',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        patients: 1300,
        experience: '19 years',
        reviews: 167,
        contact: '+91 9876543008',
        about: 'Dr. Kavita Verma is a senior pulmonologist with expertise in critical care medicine. She has extensive experience in treating complex respiratory conditions.',
        distance: '3.8 km away'
    },
    // General Medicine Doctors
    {
        id: 'doc9',
        name: 'Dr. Suresh Rao',
        specialty: 'General Physician',
        location: 'Vijayawada',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        patients: 2000,
        experience: '22 years',
        reviews: 234,
        contact: '+91 9876543009',
        about: 'Dr. Suresh Rao is a family medicine specialist providing comprehensive primary care for patients of all ages. He focuses on preventive medicine and chronic disease management.',
        distance: '1.5 km away'
    },
    {
        id: 'doc10',
        name: 'Dr. Meera Iyer',
        specialty: 'General Physician',
        location: 'Tenali',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        patients: 1800,
        experience: '18 years',
        reviews: 198,
        contact: '+91 9876543010',
        about: 'Dr. Meera Iyer is a general physician known for her patient-centered approach. She provides holistic care and emphasizes the importance of lifestyle modifications.',
        distance: '2.7 km away'
    },
    // Neurology Doctors
    {
        id: 'doc11',
        name: 'Dr. Vikram Malhotra',
        specialty: 'Neurologist',
        location: 'Vijayawada',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 1100,
        experience: '20 years',
        reviews: 156,
        contact: '+91 9876543011',
        about: 'Dr. Vikram Malhotra is a leading neurologist specializing in stroke treatment and neurological disorders. His research has contributed to several breakthrough treatments.',
        distance: '2.8 km away'
    },
    {
        id: 'doc12',
        name: 'Dr. Anjali Desai',
        specialty: 'Neurologist',
        location: 'Guntur',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        patients: 950,
        experience: '17 years',
        reviews: 134,
        contact: '+91 9876543012',
        about: 'Dr. Anjali Desai is a neurologist specializing in epilepsy and movement disorders. She provides comprehensive care for patients with complex neurological conditions.',
        distance: '3.4 km away'
    },
    // Gastroenterology Doctors
    {
        id: 'doc13',
        name: 'Dr. Harish Gupta',
        specialty: 'Gastroenterologist',
        location: 'Vijayawada',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        patients: 1300,
        experience: '19 years',
        reviews: 178,
        contact: '+91 9876543013',
        about: 'Dr. Harish Gupta is a gastroenterologist specializing in digestive disorders and endoscopy procedures. He provides advanced treatment for gastrointestinal conditions.',
        distance: '1.9 km away'
    },
    {
        id: 'doc14',
        name: 'Dr. Sunita Kapoor',
        specialty: 'Gastroenterologist',
        location: 'Tenali',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        patients: 1000,
        experience: '15 years',
        reviews: 145,
        contact: '+91 9876543014',
        about: 'Dr. Sunita Kapoor is a gastroenterologist with expertise in liver diseases and inflammatory bowel conditions. She provides personalized treatment plans.',
        distance: '2.6 km away'
    },
    // Laboratory Doctors
    {
        id: 'doc15',
        name: 'Dr. Deepak Sharma',
        specialty: 'Pathologist',
        location: 'Vijayawada',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?q=80&w=600&auto=format&fit=crop',
        patients: 800,
        experience: '16 years',
        reviews: 112,
        contact: '+91 9876543015',
        about: 'Dr. Deepak Sharma is a pathologist specializing in clinical pathology and laboratory medicine. He ensures accurate diagnosis through advanced laboratory testing.',
        distance: '2.3 km away'
    },
    {
        id: 'doc16',
        name: 'Dr. Rekha Menon',
        specialty: 'Pathologist',
        location: 'Guntur',
        rating: 4.7,
        image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?q=80&w=600&auto=format&fit=crop',
        patients: 700,
        experience: '14 years',
        reviews: 98,
        contact: '+91 9876543016',
        about: 'Dr. Rekha Menon is a pathologist with expertise in cytopathology and molecular diagnostics. She provides precise diagnostic services.',
        distance: '3.1 km away'
    },
    // Vaccination Specialists
    {
        id: 'doc17',
        name: 'Dr. Manoj Kumar',
        specialty: 'Immunologist',
        location: 'Vijayawada',
        rating: 4.9,
        image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?q=80&w=600&auto=format&fit=crop',
        patients: 1500,
        experience: '18 years',
        reviews: 189,
        contact: '+91 9876543017',
        about: 'Dr. Manoj Kumar is an immunologist specializing in vaccination and immunization programs. He provides comprehensive immunization services for all age groups.',
        distance: '1.7 km away'
    },
    {
        id: 'doc18',
        name: 'Dr. Lakshmi Devi',
        specialty: 'Pediatrician',
        location: 'Tenali',
        rating: 4.8,
        image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?q=80&w=600&auto=format&fit=crop',
        patients: 1200,
        experience: '15 years',
        reviews: 156,
        contact: '+91 9876543018',
        about: 'Dr. Lakshmi Devi is a pediatrician specializing in child immunization and vaccination schedules. She ensures children receive proper vaccination protection.',
        distance: '2.4 km away'
    },

];

export const hospitalsData = [
    // Cardiology Hospitals
    {
        id: 'hosp1',
        name: 'Heart Care Center',
        specialty: 'Cardiology Hospital',
        location: 'Vijayawada',
        rating: 4.9,
        image: 'https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 3500,
        experience: '20 years',
        reviews: 289,
        contact: '+91 9939069288',
        about: 'Heart Care Center is a specialized cardiology hospital providing advanced cardiac care with state-of-the-art equipment and experienced cardiologists.',
        distance: '2.1 km away'
    },
    {
        id: 'hosp2',
        name: 'Cardiac Care Institute',
        specialty: 'Cardiology Clinic',
        location: 'Guntur',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 2800,
        experience: '18 years',
        reviews: 234,
        contact: '+91 9876543211',
        about: 'Cardiac Care Institute offers comprehensive cardiac services including diagnostic procedures, interventional cardiology, and cardiac rehabilitation.',
        distance: '3.4 km away'
    },
    // Dentistry Hospitals
    {
        id: 'hosp3',
        name: 'Bright Smile Dental',
        specialty: 'Dental Clinic',
        location: 'Vijayawada',
        rating: 4.7,
        image: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 1200,
        experience: '15 years',
        reviews: 156,
        contact: '+91 9876543212',
        about: 'Bright Smile Dental provides comprehensive dental care with modern technology and experienced professionals. We offer cosmetic dentistry and orthodontic treatments.',
        distance: '1.8 km away'
    },
    {
        id: 'hosp4',
        name: 'Perfect Smile Dental',
        specialty: 'Dental Hospital',
        location: 'Tenali',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 950,
        experience: '12 years',
        reviews: 134,
        contact: '+91 9876543213',
        about: 'Perfect Smile Dental is a modern dental hospital offering advanced treatments including dental implants, root canals, and cosmetic procedures.',
        distance: '2.7 km away'
    },
    // Pulmonary Hospitals
    {
        id: 'hosp5',
        name: 'Lung Care Center',
        specialty: 'Pulmonary Hospital',
        location: 'Vijayawada',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 2200,
        experience: '16 years',
        reviews: 178,
        contact: '+91 9876543214',
        about: 'Lung Care Center specializes in respiratory disorders and pulmonary medicine. We provide comprehensive care for asthma, COPD, and other lung conditions.',
        distance: '2.9 km away'
    },
    {
        id: 'hosp6',
        name: 'Respiratory Health Institute',
        specialty: 'Pulmonary Clinic',
        location: 'Guntur',
        rating: 4.7,
        image: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 1800,
        experience: '14 years',
        reviews: 145,
        contact: '+91 9876543215',
        about: 'Respiratory Health Institute offers advanced pulmonary care with specialized equipment for respiratory function testing and treatment.',
        distance: '3.6 km away'
    },
    // General Hospitals
    {
        id: 'hosp7',
        name: 'Sunrise Health Hospital',
        specialty: 'General Hospital',
        location: 'Vijayawada',
        rating: 4.9,
        image: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 4500,
        experience: '25 years',
        reviews: 345,
        contact: '+91 9876543216',
        about: 'Sunrise Health Hospital is a state-of-the-art medical facility providing comprehensive healthcare services. We are committed to excellence in patient care.',
        distance: '1.5 km away'
    },
    {
        id: 'hosp8',
        name: 'City General Hospital',
        specialty: 'General Hospital',
        location: 'Tenali',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patients: 3800,
        experience: '22 years',
        reviews: 298,
        contact: '+91 9876543217',
        about: 'City General Hospital provides comprehensive medical care with a focus on community health. We offer emergency services and specialized treatments.',
        distance: '2.3 km away'
    },
    // Neurology Hospitals
    {
        id: 'hosp9',
        name: 'Brain & Spine Center',
        specialty: 'Neurology Hospital',
        location: 'Vijayawada',
        rating: 4.9,
        image: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 2800,
        experience: '18 years',
        reviews: 189,
        contact: '+91 9876543218',
        about: 'Brain & Spine Center is a specialized neurology hospital offering advanced treatment for neurological disorders, stroke care, and neurosurgical procedures.',
        distance: '2.8 km away'
    },
    {
        id: 'hosp10',
        name: 'Neurological Institute',
        specialty: 'Neurology Clinic',
        location: 'Guntur',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 2200,
        experience: '16 years',
        reviews: 167,
        contact: '+91 9876543219',
        about: 'Neurological Institute provides comprehensive neurological care including epilepsy treatment, movement disorders, and neuro-rehabilitation services.',
        distance: '3.2 km away'
    },
    // Gastroenterology Hospitals
    {
        id: 'hosp11',
        name: 'Digestive Health Center',
        specialty: 'Gastroenterology Hospital',
        location: 'Vijayawada',
        rating: 4.7,
        image: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patients: 1900,
        experience: '14 years',
        reviews: 145,
        contact: '+91 9876543220',
        about: 'Digestive Health Center specializes in gastrointestinal disorders and endoscopy procedures. We provide advanced treatment for digestive system conditions.',
        distance: '2.1 km away'
    },
    {
        id: 'hosp12',
        name: 'Gastro Care Institute',
        specialty: 'Gastroenterology Clinic',
        location: 'Tenali',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 1600,
        experience: '12 years',
        reviews: 134,
        contact: '+91 9876543221',
        about: 'Gastro Care Institute offers comprehensive gastrointestinal care including colonoscopy, liver disease treatment, and inflammatory bowel disease management.',
        distance: '2.9 km away'
    },
    // Laboratory Hospitals
    {
        id: 'hosp13',
        name: 'Advanced Diagnostics Lab',
        specialty: 'Laboratory',
        location: 'Vijayawada',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/2324837/pexels-photo-2324837.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 2500,
        experience: '18 years',
        reviews: 189,
        contact: '+91 9876543222',
        about: 'Advanced Diagnostics Lab provides comprehensive laboratory testing services with state-of-the-art equipment and accurate results for all types of medical tests.',
        distance: '1.9 km away'
    },
    {
        id: 'hosp14',
        name: 'Precision Pathology Lab',
        specialty: 'Laboratory',
        location: 'Guntur',
        rating: 4.7,
        image: 'https://images.pexels.com/photos/5794040/pexels-photo-5794040.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        patients: 2100,
        experience: '15 years',
        reviews: 167,
        contact: '+91 9876543223',
        about: 'Precision Pathology Lab specializes in pathological testing and diagnostic services. We provide accurate and timely results for better patient care.',
        distance: '2.8 km away'
    },
    // Vaccination Centers
    {
        id: 'hosp15',
        name: 'Immunization Center',
        specialty: 'Vaccination Center',
        location: 'Vijayawada',
        rating: 4.9,
        image: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 3200,
        experience: '20 years',
        reviews: 234,
        contact: '+91 9876543224',
        about: 'Immunization Center provides comprehensive vaccination services for all age groups. We offer routine immunizations and travel vaccines with expert care.',
        distance: '2.2 km away'
    },
    {
        id: 'hosp16',
        name: 'Vaccine Care Clinic',
        specialty: 'Vaccination Clinic',
        location: 'Tenali',
        rating: 4.8,
        image: 'https://images.pexels.com/photos/1692693/pexels-photo-1692693.jpeg?auto=compress&cs=tinysrgb&w=600',
        patients: 2800,
        experience: '17 years',
        reviews: 198,
        contact: '+91 9876543225',
        about: 'Vaccine Care Clinic specializes in child and adult immunization programs. We ensure safe and effective vaccination with proper follow-up care.',
        distance: '3.1 km away'
    }
];
